### ISSUE TITLE
Screenshots Issue

### ISSUE THREAD

**Issue by Soloman-Baobab** [PetrisGR/FiveM-DiscordLogs#1]
I have an issue where the screenshot will imbed into the log message and also give a separate message with just the screenshot. How can I get rid of the separate screenshot?
![622158ed961a578cc2b9096f2cb8d456](https://github.com/user-attachments/assets/ba230a38-26af-4d9d-bdfa-6f97b3dd4173)

**Comment by PetrisGR** [comment]
Hello. You can easily create an exclusive channel and webhook only for the screenshots. Then, you'll just configure the webhook in  the config.lua file.

```
Webhooks = {
        ["screenshots"] = "yourwebhookhere",  
```
