### ISSUE TITLE
Create a Player Death log

### ISSUE THREAD

**Issue by Soloman-Baobab** [PetrisGR/FiveM-DiscordLogs#2]
Could you add a log for player deaths? Would be nice to log who was killed, who did the killing, what weapon was used etc.

**Comment by PetrisGR** [comment]
Hello! Thanks for your suggestion. I haven't done that because most used frameworks offer their death logs, and I thought that you can easily adapt my logs on them. However, it is a feature that may come in the future.

**Comment by Soloman-Baobab** [comment]
> Hello! Thanks for your suggestion. I haven't done that because most used frameworks offer their death logs, and I thought that you can easily adapt my logs on them. However, it is a feature that may come in the future.



> Hello! Thanks for your suggestion. I haven't done that because most used frameworks offer their death logs, and I thought that you can easily adapt my logs on them. However, it is a feature that may come in the future.

I have been experimenting with but have not been able to figure it out. I use ESX and visn_are (advance roleplay environment 2) and have tried registering their death queries to trigger the export for the log. No luck. Should I be putting the log export within your resource? or should I be putting your export into ESX/visn_are?
